# Explanation Evidence - Phase 7.14
# ===================================

"""
Evidence for explanatory reasoning.

An ExplanationEvidence represents a single piece of evidence supporting or 
challenging an explanation.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any
from enum import Enum, auto


class EvidenceKind(Enum):
    """Kinds of evidence in explanatory reasoning."""
    
    PERCEPTION = "perception"           # Direct sensory observation
    MEMORY = "memory"                   # Recalled information
    KNOWLEDGE = "knowledge"             # General factual knowledge
    REASONING = "reasoning"             # Derived from other reasoning
    SIMULATION = "simulation"           # Generated by simulation
    EXTERNAL_TOOL = "external_tool"     # From external tools


class EvidenceRelevance(Enum):
    """How relevant evidence is to an explanation."""
    
    CRITICAL = "critical"               # Essential for the explanation
    SUPPORTING = "supporting"           # Supports but not essential
    NEUTRAL = "neutral"                 # Neither supports nor contradicts
    CONTRADICTORY = "contradictory"     # Challenges the explanation


@dataclass(frozen=True)
class EvidenceIdentity:
    """
    Immutable identity for an evidence item.
    
    Allows replay and verification of evidentiary analysis.
    """
    
    # Core identity
    semantic_identity: str                    # Stable identity across runs
    
    # Item context
    item_number: int = 1                      # For repeated evaluations
    timestamp_utc: float = field(default_factory=time.time)
    
    @classmethod
    def create(cls, semantic_identity: str, item_number: int = 1) -> EvidenceIdentity:
        """Create a new evidence identity."""
        return cls(
            semantic_identity=semantic_identity,
            item_number=item_number,
        )


@dataclass(frozen=True)
class ExplanationEvidence:
    """
    A single piece of evidence in explanatory reasoning.
    
    Evidence may originate from:
        - Perception (direct observation)
        - Memory (recalled information)
        - Knowledge (general facts)
        - Reasoning (derived conclusions)
        - Simulation (generated outputs)
        - External tools (external data sources)
    
    Each evidence item records:
        - Its source and kind
        - Relevance to the explanation
        - Reliability assessment
        - Provenance information
    """
    
    # Identity
    evidence_id: str                          # Unique identifier
    semantic_identity: str                    # Stable identity across runs
    
    # Content
    evidence_content: Dict[str, Any]          # The actual evidence data
    evidence_kind: EvidenceKind               # Where did this come from?
    
    # Relevance to explanation
    relevant_claims: Tuple[str, ...]          # Which claims does this support?
    relevance_level: EvidenceRelevance        # How relevant is it?
    
    # Quality metrics
    reliability: float = 0.5                  # Reliability score (0.0-1.0)
    confidence: float = 0.5                   # Confidence in the evidence
    
    # Context
    context_tags: Tuple[str, ...] = ()        # Tags for organization
    temporal_marker: Optional[float] = None   # When did this occur?
    
    @property
    def strength(self) -> float:
        """Calculate evidentiary strength."""
        return self.reliability * self.confidence
    
    @property
    def is_supporting(self) -> bool:
        """Check if evidence supports the explanation."""
        return self.relevance_level in (EvidenceRelevance.CRITICAL, EvidenceRelevance.SUPPORTING)
    
    @property
    def is_challenging(self) -> bool:
        """Check if evidence challenges the explanation."""
        return self.relevance_level == EvidenceRelevance.CONTRADICTORY
    
    @classmethod
    def create(
        cls,
        evidence_content: Dict[str, Any],
        relevant_claims: List[str],
        evidence_kind: EvidenceKind = EvidenceKind.PERCEPTION,
        relevance_level: EvidenceRelevance = EvidenceRelevance.SUPPORTING,
        reliability: float = 0.5,
        confidence: float = 0.5,
        context_tags: Optional[List[str]] = None,
    ) -> ExplanationEvidence:
        """Create a new evidence item."""
        return cls(
            evidence_id=f"evidence:{uuid.uuid4().hex[:16]}",
            semantic_identity=relevant_claims[0] if relevant_claims else "unknown",
            evidence_content=evidence_content,
            evidence_kind=evidence_kind,
            relevant_claims=tuple(relevant_claims),
            relevance_level=relevance_level,
            reliability=reliability,
            confidence=confidence,
            context_tags=tuple(context_tags or []),
        )
    
    def with_revised_reliability(self, new_reliability: float) -> ExplanationEvidence:
        """Return a copy with revised reliability."""
        return dataclass_replace(
            self,
            reliability=new_reliability,
            confidence=min(new_reliability, self.confidence),  # Confidence can't exceed reliability
        )
    
    def strengthen_confidence(self, amount: float = 0.1) -> ExplanationEvidence:
        """Increase confidence by a small amount."""
        return dataclass_replace(
            self,
            confidence=min(1.0, self.confidence + amount),
        )


@dataclass(frozen=True)
class EvidenceAggregation:
    """
    Aggregated evidence set for explanatory reasoning.
    
    Evaluates:
        - Relevance
        - Coverage
        - Reliability
        - Consistency
        - Independence
        - Completeness
    """
    
    # Identity
    aggregation_id: str                       # Unique identifier
    
    # Participating evidence
    participating_evidence: Tuple[ExplanationEvidence, ...]
    
    # Aggregation metrics
    total_count: int = 0                      # Total items
    supporting_count: int = 0                 # Supporting evidence count
    challenging_count: int = 0                # Challenging evidence count
    
    # Quality metrics
    average_reliability: float = 0.5          # Average reliability
    average_confidence: float = 0.5           # Average confidence
    source_diversity: int = 1                 # Number of unique sources
    
    @property
    def net_strength(self) -> float:
        """Calculate net evidentiary strength."""
        if self.total_count == 0:
            return 0.0
        return (
            (self.supporting_count * self.average_reliability) -
            (self.challenging_count * self.average_reliability)
        ) / max(self.total_count, 1)
    
    @property
    def coverage_score(self) -> float:
        """Calculate evidence coverage score."""
        if self.source_diversity == 0 or self.total_count == 0:
            return 0.0
        # More sources = better coverage (up to a point)
        source_score = min(1.0, self.source_diversity / 3.0)
        return (
            self.average_confidence * 0.4 +
            source_score * 0.4 +
            min(1.0, self.total_count / 5.0) * 0.2
        )
    
    def filter_by_kind(self, kind: EvidenceKind) -> "EvidenceAggregation":
        """Return a filtered aggregation containing only evidence of specified kind."""
        filtered = tuple(
            e for e in self.participating_evidence
            if e.evidence_kind == kind
        )
        
        supporting = sum(1 for e in filtered if e.is_supporting)
        challenging = sum(1 for e in filtered if e.is_challenging)
        
        return dataclass_replace(
            self,
            participating_evidence=filtered,
            total_count=len(filtered),
            supporting_count=supporting,
            challenging_count=challenging,
        )
    
    @classmethod
    def create(
        cls,
        evidence_items: List[ExplanationEvidence],
    ) -> "EvidenceAggregation":
        """Create a new evidence aggregation."""
        items = tuple(evidence_items)
        
        sources = set()
        for item in items:
            content = item.evidence_content
            if isinstance(content, dict):
                source = content.get("source", "")
                if source:
                    sources.add(source)
        
        supporting = sum(1 for e in items if e.is_supporting)
        challenging = sum(1 for e in items if e.is_challenging)
        
        avg_reliability = (
            sum(e.reliability for e in items) / max(len(items), 1)
        )
        avg_confidence = (
            sum(e.confidence for e in items) / max(len(items), 1)
        )
        
        return cls(
            aggregation_id=f"evidence_agg:{uuid.uuid4().hex[:16]}",
            participating_evidence=items,
            total_count=len(items),
            supporting_count=supporting,
            challenging_count=challenging,
            average_reliability=avg_reliability,
            average_confidence=avg_confidence,
            source_diversity=len(sources),
        )


def dataclass_replace(instance: Any, **kwargs: Any) -> Any:
    """Simple dataclass replace helper for frozen instances."""
    return instance.__class__(**{**instance.__dict__, **kwargs})


__all__ = [
    "EvidenceIdentity",
    "ExplanationEvidence",
    "EvidenceAggregation",
    "EvidenceKind",
    "EvidenceRelevance",
]