# Thought Factory - Construction and Validation
# ==============================================

"""
ThoughtFactory for constructing InternalThought instances.

This module provides a separate construction mechanism from generation,
following the factory pattern to separate:
    - Object instantiation (factory)
    - Generation logic (generator)

ARCHITECTURAL PRINCIPLE:
    Factory creates valid thoughts.
    Generator decides what thoughts to create.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Tuple, Optional, Dict, Any
from datetime import datetime
from uuid import uuid4


@dataclass(frozen=True, slots=True)
class ThoughtFactory:
    """
    Factory for constructing InternalThought instances with validation.
    
    Responsibilities:
        - Instantiate typed thoughts
        - Validate invariants
        - Assign identifiers
        - Assign revisions
        - Assign metadata
        
    No reasoning logic belongs here. This is purely construction and validation.
    
    ARCHITECTURAL INVARIANTS:
        FACTORY-INV-001: Factory never executes behavior
        FACTORY-INV-002: Factory never invokes Executive
        FACTORY-INV-003: Factory never schedules threads
        FACTORY-INV-004: Factory produces immutable objects only
        
    USAGE PATTERN:
        Thoughts are generated by ThoughtGenerator based on context.
        ThoughtFactory ensures all generated thoughts are valid and consistent.
    """
    
    # Factory configuration
    maximum_concept_length: int = 1000
    """Maximum allowed length for concept strings."""
    
    maximum_associations: int = 50
    """Maximum associations per thought."""
    
    minimum_confidence_required: float = 0.3
    """Minimum confidence threshold for valid thoughts."""
    
    def new_thought(
        self,
        concept: str,
        purpose: str,
        thought_kind: str,
        originating_episode_id: Optional[str] = None,
        originating_context_version: str = "",
        generator_type: str = "default",
        assessment: Optional[Dict[str, Any]] = None,
    ) -> Tuple[bool, Any]:
        """
        Create a new thought with validation.
        
        Args:
            concept: Core semantic concept (bounded representation)
            purpose: Cognitive purpose of this thought
            thought_kind: Canonical category of cognition
            originating_episode_id: ID of episode triggering generation
            originating_context_version: Context version reference
            generator_type: Type of generator creating this thought
            assessment: Optional assessment metrics dictionary
            
        Returns:
            Tuple of (success, thought_or_error_message)
        """
        # Validate concept length
        if len(concept) > self.maximum_concept_length:
            return False, f"Concept exceeds maximum length ({len(concept)} > {self.maximum_concept_length})"
        
        # Validate purpose
        if not purpose or not isinstance(purpose, str):
            return False, "Purpose must be a non-empty string"
        
        # Validate kind
        from .enums import InternalThoughtKind
        valid_kinds = set(InternalThoughtKind.all_kinds())
        if thought_kind not in valid_kinds:
            return False, f"Invalid thought kind: {thought_kind}"
        
        # Build provenance
        provenance = {
            "originating_episode_id": originating_episode_id or "",
            "originating_context_version": originating_context_version,
            "generator_type": generator_type,
            "generated_at_utc": datetime.utcnow().isoformat(),
            "configuration_hash": "",
        }
        
        # Validate assessment metrics if provided
        confidence = 0.5
        if assessment:
            confidence = float(assessment.get("confidence", 0.5))
            if not (0.0 <= confidence <= 1.0):
                return False, f"Confidence must be between 0.0 and 1.0: {confidence}"
            
            # Check minimum confidence requirement
            if confidence < self.minimum_confidence_required:
                return False, f"Confidence below threshold ({confidence} < {self.minimum_confidence_required})"
        
        thought_id = f"thought:{uuid4().hex[:24]}"
        revision = 1
        
        from .thought import InternalThought, ThoughtAssessmentMetrics, ThoughtProvenance
        from datetime import datetime as dt
        
        thought = InternalThought(
            thought_id=thought_id,
            thought_kind=thought_kind,
            concept=concept,
            purpose=purpose,
            provenance=ThoughtProvenance(
                originating_episode_id=originating_episode_id or "",
                originating_context_version=originating_context_version,
                generator_type=generator_type,
                generated_at_utc=dt.utcnow(),
                validated_at_utc=None,
                configuration_hash="",
                initial_revision=revision,
            ),
            originating_episode_id=originating_episode_id,
            originating_context_version=originating_context_version,
            assessment=ThoughtAssessmentMetrics(
                confidence=confidence,
                novelty=float(assessment.get("novelty", 0.0)),
                expected_utility=float(assessment.get("expected_utility", 0.0)),
                relevance=float(assessment.get("relevance", 0.5)),
                consistency=float(assessment.get("consistency", 0.5)),
                coherence=float(assessment.get("coherence", 0.5)),
                risk=float(assessment.get("risk", 0.0)),
                urgency=float(assessment.get("urgency", 0.0)),
            ) if assessment else ThoughtAssessmentMetrics(),
            lifecycle_state="generated",
            relationships=(),
            revision=revision,
        )
        
        return True, thought
    
    def from_dict(
        self,
        data: Dict[str, Any],
    ) -> Tuple[bool, Any]:
        """
        Reconstruct a thought from dictionary representation.
        
        Args:
            data: Dictionary containing thought serialization
            
        Returns:
            Tuple of (success, thought_or_error_message)
        """
        # Basic validation
        required_fields = ["thought_id", "thought_kind", "concept", "purpose"]
        for field_name in required_fields:
            if field_name not in data:
                return False, f"Missing required field: {field_name}"
        
        # Validate concept length
        if len(data.get("concept", "")) > self.maximum_concept_length:
            return False, "Concept exceeds maximum length"
        
        from .thought import InternalThought
        
        try:
            thought = InternalThought.from_dict(data)
            return True, thought
        except Exception as e:
            return False, f"Failed to deserialize thought: {str(e)}"
    
    def update_lifecycle(
        self,
        thought: Any,  # InternalThought
        new_state: str,
    ) -> Tuple[bool, Any]:
        """
        Update the lifecycle state of an existing thought.
        
        Args:
            thought: The thought to update
            new_state: New lifecycle state
            
        Returns:
            Tuple of (success, updated_thought_or_error_message)
        """
        # Validate state
        from .enums import LifecycleState
        valid_states = set(LifecycleState.all_states())
        
        if new_state not in valid_states:
            return False, f"Invalid lifecycle state: {new_state}"
        
        updated_thought = thought.with_lifecycle(new_state)
        return True, updated_thought
    
    def add_relationship(
        self,
        thought: Any,  # InternalThought
        relationship_kind: str,
        target_thought_id: str,
    ) -> Tuple[bool, Any]:
        """
        Add a relationship to an existing thought.
        
        Args:
            thought: The thought to update
            relationship_kind: Type of relationship
            target_thought_id: ID of target thought
            
        Returns:
            Tuple of (success, updated_thought_or_error_message)
        """
        # Validate kind
        from .enums import RelationshipKind
        valid_kinds = set(RelationshipKind.all_kinds())
        
        if relationship_kind not in valid_kinds:
            return False, f"Invalid relationship kind: {relationship_kind}"
        
        # Validate target ID format
        if not isinstance(target_thought_id, str) or len(target_thought_id) < 3:
            return False, "Invalid target thought ID"
        
        updated_thought = thought.with_relationship(relationship_kind, target_thought_id)
        return True, updated_thought
    
    def create_revision(
        self,
        thought: Any,  # InternalThought
        new_concept: str,
    ) -> Tuple[bool, Any]:
        """
        Create a new revision of an existing thought.
        
        Args:
            thought: The original thought to revise
            new_concept: Updated semantic content
            
        Returns:
            Tuple of (success, revised_thought_or_error_message)
        """
        # Validate new concept length
        if len(new_concept) > self.maximum_concept_length:
            return False, "New concept exceeds maximum length"
        
        updated_thought = thought.with_revision(new_concept)
        return True, updated_thought


def create_factory(
    maximum_concept_length: int = 1000,
    minimum_confidence_required: float = 0.3,
) -> ThoughtFactory:
    """
    Factory function to create a configuredThoughtFactory.
    
    Args:
        maximum_concept_length: Maximum allowed concept length
        minimum_confidence_required: Minimum confidence threshold
        
    Returns:
        Configured ThoughtFactory instance
    """
    return ThoughtFactory(
        maximum_concept_length=maximum_concept_length,
        minimum_confidence_required=minimum_confidence_required,
    )