# Focusing Network Enums
# =======================

"""
Focusing-specific enumerations.

These define bounded categorical types used throughout the FocusingNetwork.
All enums are immutable and hashable for deterministic behavior.
"""

from enum import Enum, auto


class FocusModality(Enum):
    """
    Attention modality or focus type.
    
    Represents the nature of attention allocation. Does not imply any specific
    implementation - those belong to Perception, Reasoning, etc.
    """

    VISUAL = "visual"
    AUDITORY = "auditory"
    TACTILE = "tactile"
    COGNITIVE = "cognitive"
    EXECUTIVE = "executive"
    WORKSPACE = "workspace"

    # Generic / unknown
    GENERIC = "generic"
    UNKNOWN = "unknown"

    def is_cognitive(self) -> bool:
        """Return True if modality involves reasoning or memory."""
        return self in (FocusModality.COGNITIVE, FocusModality.WORKSPACE)


class FocusSource(Enum):
    """
    Origin of the focus candidate.

    Indicates where a potential focus target comes from without embedding
    implementation details. Source identity belongs to higher layers.
    """

    # Endogenous sources (internal)
    GOAL = "goal"  # From current objectives
    PLAN = "plan"  # From active plans
    TASK = "task"  # From task context
    MEMORY = "memory"  # Retrieved from memory systems
    REASONING = "reasoning"  # Generated by reasoning processes

    # Exogenous sources (external)
    PERCEPTION = "perception"  # Sensory input via Perception systems
    ENVIRONMENT = "environment"  # External environmental signals

    # System-generated sources
    INTERNAL_MONITOR = "internal_monitor"
    METACOGNITION = "metacognition"

    # Generic / unknown
    GENERIC = "generic"
    UNKNOWN = "unknown"

    def is_endogenous(self) -> bool:
        """Return True if source is generated internally."""
        return self in (
            FocusSource.GOAL,
            FocusSource.PLAN,
            FocusSource.TASK,
            FocusSource.MEMORY,
            FocusSource.REASONING,
            FocusSource.INTERNAL_MONITOR,
            FocusSource.METACOGNITION,
        )

    def is_exogenous(self) -> bool:
        """Return True if source is external to the agent."""
        return self in (FocusSource.PERCEPTION, FocusSource.ENVIRONMENT)


class PriorityLevel(Enum):
    """
    Bounded priority classification.

    Describes the strength of focus allocation recommendation.
    Does NOT authorize behavior - only advises resource allocation.

    Levels:
        NEGLIGIBLE: No sustained attention needed
        LOW: Minor relevance, optional allocation
        MEDIUM: Some goal relevance, consider allocation
        HIGH: Strong goal alignment, recommend allocation
        CRITICAL: High priority for current objectives
    """

    NEGLIGIBLE = "negligible"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

    @classmethod
    def from_score(cls, score: float) -> "PriorityLevel":
        """
        Infer level from a priority score.

        This is a convenience method for testing or debugging.
        The actual assessment comes from configuration-defined thresholds.
        """
        if score < 0.1:
            return cls.NEGLIGIBLE
        elif score < 0.3:
            return cls.LOW
        elif score < 0.5:
            return cls.MEDIUM
        elif score < 0.8:
            return cls.HIGH
        else:
            return cls.CRITICAL

    def requires_focusing(self) -> bool:
        """Return True if this level warrants focus allocation."""
        return self in (PriorityLevel.LOW, PriorityLevel.MEDIUM,
                       PriorityLevel.HIGH, PriorityLevel.CRITICAL)


class PrecisionBandwidth(Enum):
    """
    Attention precision or bandwidth classification.

    Describes how finely resources should be allocated.
    """

    COARSE = "coarse"  # Broad, diffuse attention
    MODERATE = "moderate"  # Standard focus
    FINE = "fine"  # Sharp, narrow attention
    ULTRA_FINE = "ultra_fine"  # Maximum precision

    @classmethod
    def from_precision(cls, precision: float) -> "PrecisionBandwidth":
        """
        Infer bandwidth from a precision score.
        
        Higher precision = finer bandwidth (narrower focus).
        """
        if precision < 0.3:
            return cls.COARSE
        elif precision < 0.6:
            return cls.MODERATE
        elif precision < 0.85:
            return cls.FINE
        else:
            return cls.ULTRA_FINE


class PersistenceMode(Enum):
    """
    Focus persistence strategy.

    Describes how focus should be maintained over time.
    """

    TRANSIENT = "transient"  # Brief attention, rapid decay
    SUSTAINED = "sustained"  # Steady maintenance
    LOCKED = "locked"  # Strong persistence, high resistance to change
    ADAPTIVE = "adaptive"  # Dynamic adjustment based on context

    def is_strict(self) -> bool:
        """Return True if mode resists attention shifts."""
        return self in (PersistenceMode.LOCKED,)


class BiasModality(Enum):
    """
    Top-down bias modality.

    Describes the source of top-down modulation.
    """

    GOAL = "goal"  # Objective-based bias
    TASK = "task"  # Task-specific bias
    MEMORY = "memory"  # Memory-based priming
    TEMPORAL = "temporal"  # Time-based anticipation
    SPATIAL = "spatial"  # Location-based attention

    def is_cognitive(self) -> bool:
        """Return True if modality involves higher-level processing."""
        return self in (BiasModality.GOAL, BiasModality.TASK,
                       BiasModality.MEMORY)


class FocusingStateTransition(Enum):
    """
    State transitions for the FocusingNetwork.

    Records how internal state evolves during assessment.
    """

    ACQUISITION = "acquisition"  # New focus acquisition
    MAINTENANCE = "maintenance"  # Continue current focus
    SHIFT = "shift"  # Change focus target
    RELEASE = "release"  # Release attention from target
    SUPPRESSION = "suppression"  # Actively suppress a target