# Reflection Outcome Models
# ==========================

"""
Immutable models for reflection outcomes, proposals, and continuation.

ARCHITECTURAL PRINCIPLES:
    - Outcomes are terminal results, not runtime commands
    - Proposals remain advisory (never automatically applied)
    - Continuation recommendations do NOT schedule execution
    - No runtime dependencies
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Tuple, Optional


# =============================================================================
# PROPOSAL KINDS (re-exported for convenience)
# =============================================================================

class ProposalKind:
    """
    Canonical kinds of proposals generated by reflection.
    
    Proposals remain advisory. They are suggestions to be interpreted
    and acted upon by authorized authorities.
    """
    
    MEMORY_UPDATE = "memory_update"
    """Propose updating memory records."""
    
    NARRATIVE_UPDATE = "narrative_update"
    """Propose updating narrative structure."""
    
    IDENTITY_REVIEW = "identity_review"
    """Propose identity review coordination."""
    
    IDENTITY_UPDATE = "identity_update"
    """Propose identity model update (not applied directly)."""
    
    POLICY_REVIEW = "policy_review"
    """Propose policy review coordination."""
    
    PLAN_REVISION = "plan_revision"
    """Propose plan revision."""
    
    EXECUTION_TASK = "execution_task"
    """Propose execution task creation."""
    
    FOLLOW_UP_REFLECTION = "follow_up_reflection"
    """Propose follow-up reflection episode."""
    
    SIMULATION = "simulation"
    """Propose simulation or counterfactual exploration."""
    
    WORKSPACE_CANDIDATE = "workspace_candidate"
    """Propose workspace candidate submission."""
    
    CONCERN_CREATION = "concern_creation"
    """Propose creating a new concern."""
    
    LEARNING_UPDATE = "learning_update"
    """Propose learning adaptation (not applied directly)."""


# =============================================================================
# REFLECTION OUTCOME
# =============================================================================

@dataclass(frozen=True, slots=True)
class ReflectionOutcome:
    """
    Immutable terminal result of a reflection episode.
    
    An outcome represents what the reflection episode produced,
    not any runtime action that should follow. Outcomes remain
    proposals until acted upon by authorized authorities.
    
    PROPERTIES:
        • outcome_id: Unique identifier
        • kind: What type of outcome (ReflectionOutcomeKind.*)
        • products_accepted: Products that passed validation
        • products_rejected: Products that failed validation
        • unresolved_products: Products needing further review
        • confidence: Overall confidence in outcome
        • completeness: Completeness assessment
        
    BOUNDEDNESS:
        All product collections must be bounded.
    
    NOT RESPONSIBLE FOR:
        - Mutating source data directly
        - Scheduling runtime execution
        - Creating memory records
    """
    
    outcome_id: str
    """Unique identifier for this outcome."""
    
    kind: str  # ReflectionOutcomeKind.*
    """The canonical kind of outcome produced."""
    
    products_accepted: Tuple[str, ...] = field(default_factory=tuple)
    """IDs of accepted reflective products (insights, patterns, etc.)."""
    
    products_rejected: Tuple[str, ...] = field(default_factory=tuple)
    """IDs of rejected products and reasons."""
    
    unresolved_products: Tuple[str, ...] = field(default_factory=tuple)
    """IDs of products needing further review."""
    
    confidence: float = 0.5
    """Confidence in this outcome (0.0 to 1.0)."""
    
    completeness: str = "unknown"
    """Completeness status: 'complete', 'sufficient', 'partial', 'insufficient'"""
    
    limitations: Tuple[str, ...] = field(default_factory=tuple)
    """Known limitations of this outcome."""
    
    follow_up_proposals: Tuple[str, ...] = field(default_factory=tuple)
    """Follow-up proposal references."""
    
    integration_proposals: Tuple[str, ...] = field(default_factory=tuple)
    """Integration proposal references (memory, narrative, etc.)."""
    
    provenance: Optional[str] = None
    """Provenance reference for this outcome."""
    
    @classmethod
    def insights_produced(
        cls,
        outcome_id: str,
        insight_ids: Tuple[str, ...],
        confidence: float = 0.7,
    ) -> ReflectionOutcome:
        """Create an outcomes-produced outcome."""
        return cls(
            outcome_id=outcome_id,
            kind="insights_produced",
            products_accepted=insight_ids,
            confidence=confidence,
            completeness="complete" if len(insight_ids) >= 1 else "partial",
        )
    
    @classmethod
    def patterns_identified(
        cls,
        outcome_id: str,
        pattern_ids: Tuple[str, ...],
        exception_ids: Tuple[str, ...] = (),
        confidence: float = 0.7,
    ) -> ReflectionOutcome:
        """Create a patterns-identified outcome."""
        return cls(
            outcome_id=outcome_id,
            kind="patterns_identified",
            products_accepted=pattern_ids + exception_ids,
            confidence=confidence,
        )
    
    @classmethod
    def contradictions_identified(
        cls,
        outcome_id: str,
        contradiction_ids: Tuple[str, ...],
    ) -> ReflectionOutcome:
        """Create a contradictions-identified outcome."""
        return cls(
            outcome_id=outcome_id,
            kind="contradictions_identified",
            products_accepted=contradiction_ids,
            confidence=1.0,  # Contradictions are factual if detected correctly
            completeness="complete",
        )
    
    @classmethod
    def no_meaningful_result(cls, outcome_id: str) -> ReflectionOutcome:
        """Create a no-meaningful-result outcome."""
        return cls(
            outcome_id=outcome_id,
            kind="no_meaningful_result",
            confidence=1.0,
            completeness="complete",
        )
    
    @classmethod
    def insufficient_context(cls, outcome_id: str) -> ReflectionOutcome:
        """Create an insufficient-context outcome."""
        return cls(
            outcome_id=outcome_id,
            kind="insufficient_context",
            confidence=0.0,
            completeness="insufficient",
        )
    
    @classmethod
    def failed(
        cls,
        outcome_id: str,
        failure_reason: str,
    ) -> ReflectionOutcome:
        """Create a failed outcome."""
        return cls(
            outcome_id=outcome_id,
            kind="failed",
            limitations=(failure_reason,),
            confidence=0.0,
            completeness="invalid",
        )
    
    def is_success(self) -> bool:
        """Check if this outcome represents successful reflection."""
        return self.kind in {
            "insights_produced",
            "patterns_identified",
            "contradictions_identified",
            "assumptions_identified",
            "correction_proposed",
            "improvement_proposed",
            "follow_up_required",
        }
    
    def has_products(self) -> bool:
        """Check if this outcome contains any products."""
        return (
            len(self.products_accepted) > 0 or
            len(self.products_rejected) > 0 or
            len(self.unresolved_products) > 0
        )


# =============================================================================
# REFLECTION CONTINUATION RECOMMENDATIONS
# =============================================================================

@dataclass(frozen=True, slots=True)
class ReflectionContinuation:
    """
    Advisory continuation recommendation from reflection.
    
    Continuation recommendations are semantic guidance, NOT runtime
    commands. They must be interpreted by a higher-level coordinator.
    
    PROPERTIES:
        • kind: What to do next (ReflectionContinuationKind.*)
        • description: Human-readable explanation
        • proposed_next_steps: Recommended follow-up actions
        
    BOUNDEDNESS:
        Continuation must remain advisory and bounded.
    """
    
    kind: str  # ReflectionContinuationKind.*
    """The recommended continuation."""
    
    description: str = ""
    """Human-readable explanation."""
    
    proposed_next_steps: Tuple[str, ...] = field(default_factory=tuple)
    """Recommended follow-up actions or episodes."""
    
    @classmethod
    def complete(cls) -> ReflectionContinuation:
        """Create a completion recommendation."""
        return cls(
            kind="complete",
            description="Reflection completed successfully.",
        )
    
    @classmethod
    def continue_with_current_context(cls) -> ReflectionContinuation:
        """Continue with current context."""
        return cls(
            kind="continue_with_current_context",
            description="Continue processing with current context and plan.",
        )
    
    @classmethod
    def request_context_refresh(cls, reason: str = "") -> ReflectionContinuation:
        """Request a context refresh."""
        return cls(
            kind="request_context_refresh",
            description=f"Context needs refresh: {reason}" if reason else "Refresh context binding.",
        )
    
    @classmethod
    def wait_for_evidence(cls) -> ReflectionContinuation:
        """Wait for additional evidence."""
        return cls(
            kind="wait_for_evidence",
            description="Waiting for additional evidence to become available.",
        )
    
    @classmethod
    def suspend(cls, reason: str = "") -> ReflectionContinuation:
        """Suspend processing."""
        return cls(
            kind="suspend",
            description=f"Suspended: {reason}" if reason else "Processing suspended temporarily.",
        )
    
    @classmethod
    def derive_child_episode(
        cls,
        child_purpose: str,
        child_subject: str,
    ) -> ReflectionContinuation:
        """Derive a child episode."""
        return cls(
            kind="derive_child_episode",
            description=f"Create child episode for: {child_subject}",
            proposed_next_steps=(f"episode:{child_purpose}:{child_subject}",),
        )
    
    @classmethod
    def fail(cls, failure_reason: str) -> ReflectionContinuation:
        """Mark as failed."""
        return cls(
            kind="fail",
            description=f"Reflection failed: {failure_reason}",
        )
    
    @classmethod
    def cancel(cls, cancellation_reason: str) -> ReflectionContinuation:
        """Cancel the reflection."""
        return cls(
            kind="cancel",
            description=f"Reflection cancelled: {cancellation_reason}",
        )


# =============================================================================
# CONFIDENCE ASSESSMENT
# =============================================================================

@dataclass(frozen=True, slots=True)
class ReflectionConfidence:
    """
    Structured confidence assessment for reflection outcomes.
    
    Confidence measures evidential quality, not truth. High confidence
    means strong supporting evidence; low confidence means weak or
    conflicting evidence.
    
    PROPERTIES:
        • overall_confidence: Overall confidence level (0.0 to 1.0)
        • context_confidence: Confidence in the input context
        • evidence_quality: Quality of collected evidence
        • agreement_count: Number of supporting evidence items
        • contradiction_count: Number of conflicting evidence items
        
    NOT RANKED AS:
        - Importance
        - Novelty  
        - Utility
        - Truth value
    """
    
    overall_confidence: float  # 0.0 to 1.0
    """Overall confidence level."""
    
    context_confidence: float = 0.5
    """Confidence in the input context."""
    
    evidence_quality: float = 0.5
    """Quality of collected evidence (0.0 to 1.0)."""
    
    agreement_count: int = 0
    """Number of supporting evidence items."""
    
    contradiction_count: int = 0
    """Number of conflicting evidence items."""
    
    stale_inputs: Tuple[str, ...] = field(default_factory=tuple)
    """Input sources that may be outdated."""
    
    alternative_explanations: Tuple[str, ...] = field(default_factory=tuple)
    """Alternative interpretations considered."""
    
    @classmethod
    def high(cls) -> ReflectionConfidence:
        """Create a high-confidence assessment."""
        return cls(
            overall_confidence=0.8,
            context_confidence=0.9,
            evidence_quality=0.85,
            agreement_count=3,
            contradiction_count=0,
        )
    
    @classmethod
    def medium(cls) -> ReflectionConfidence:
        """Create a medium-confidence assessment."""
        return cls(
            overall_confidence=0.6,
            context_confidence=0.7,
            evidence_quality=0.65,
            agreement_count=1,
            contradiction_count=1,
        )
    
    @classmethod
    def low(cls) -> ReflectionConfidence:
        """Create a low-confidence assessment."""
        return cls(
            overall_confidence=0.3,
            context_confidence=0.4,
            evidence_quality=0.35,
            agreement_count=0,
            contradiction_count=2,
        )
    
    @classmethod
    def unknown(cls) -> ReflectionConfidence:
        """Create an unknown-confidence assessment."""
        return cls(
            overall_confidence=0.5,
            context_confidence=0.5,
            evidence_quality=0.5,
        )


# =============================================================================
# COMPLETENESS ASSESSMENT
# =============================================================================

class ReflectionCompleteness:
    """
    Structured completeness assessment for reflection.
    
    Completeness measures whether all required elements are present,
    not the quality of what is present.
    """
    
    COMPLETE = "complete"
    """All required elements present and sufficient."""
    
    SUFFICIENT = "sufficient"
    """Sufficient elements present for meaningful results."""
    
    PARTIAL = "partial"
    """Some elements present but incomplete."""
    
    INSUFFICIENT = "insufficient"
    """Not enough elements for meaningful reflection."""
    
    INVALID = "invalid"
    """Reflection context is invalid."""
    
    @classmethod
    def all_statuses(cls) -> Tuple[str, ...]:
        """Return all completeness statuses."""
        return (
            cls.COMPLETE,
            cls.SUFFICIENT,
            cls.PARTIAL,
            cls.INSUFFICIENT,
            cls.INVALID,
        )
    
    @classmethod
    def is_acceptable(cls, status: str) -> bool:
        """Check if status allows reflection to proceed."""
        return status in {cls.COMPLETE, cls.SUFFICIENT}
    
    @classmethod
    def is_terminal(cls, status: str) -> bool:
        """Check if status represents a terminal condition."""
        return status in {cls.INVALID}


@dataclass(frozen=True, slots=True)
class ReflectionCompletenessRecord:
    """
    Detailed completeness assessment for reflection.
    
    This provides granular information about what's present and what's missing.
    
    PROPERTIES:
        • overall_status: High-level completeness (ReflectionCompleteness.*)
        • required_count: How many elements are required
        • supplied_count: How many elements were found
        • missing_required: Which required elements are absent
        • optional_supplied: Optional elements that were present
        
    BOUNDEDNESS:
        All lists must be bounded.
    """
    
    overall_status: str  # ReflectionCompleteness.*
    """High-level completeness assessment."""
    
    required_count: int = 0
    """Number of required context elements."""
    
    supplied_count: int = 0
    """Number of required elements that were supplied."""
    
    missing_required: Tuple[str, ...] = field(default_factory=tuple)
    """Required elements that are missing."""
    
    optional_supplied: int = 0
    """Optional elements that were provided."""
    
    @classmethod
    def complete(cls) -> ReflectionCompletenessRecord:
        """Create a complete record."""
        return cls(
            overall_status=ReflectionCompleteness.COMPLETE,
            required_count=0,
            supplied_count=0,
        )
    
    @classmethod
    def insufficient(cls, missing: Tuple[str, ...]) -> ReflectionCompletenessRecord:
        """Create an insufficient record."""
        return cls(
            overall_status=ReflectionCompleteness.INSUFFICIENT,
            required_count=len(missing),
            supplied_count=0,
            missing_required=missing,
        )
    
    @classmethod
    def partial(cls, supplied: int, total: int) -> ReflectionCompletenessRecord:
        """Create a partial record."""
        return cls(
            overall_status=ReflectionCompleteness.PARTIAL,
            required_count=total,
            supplied_count=supplied,
            missing_required=tuple(f"element_{i}" for i in range(supplied, total)),
        )