# Probabilistic Governance - Phase 7.7
# ====================================

"""
Canonical governance contracts for probabilistic reasoning.

Governance remains observational - it never modifies artifacts directly.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any
from enum import Enum


class GovernanceFinding(Enum):
    """Findings from probabilistic governance evaluation."""
    
    INVALID_DISTRIBUTION = "invalid_distribution"       # Distribution parameters invalid
    CALIBRATION_DRIFT = "calibration_drift"              # Calibration accuracy degraded
    NONDETERMINISTIC_INFERENCE = "nondeterministic_inference"  # Results vary on same input
    MISSING_PROVENANCE = "missing_provenance"            # Evidence lacks origin info
    CYCLIC_DEPENDENCY = "cyclic_dependency"              # Circular dependency in graph


@dataclass(frozen=True)
class GovernanceViolation:
    """
    A governance violation identified during evaluation.
    
    Represents a break from expected probabilistic reasoning standards.
    """
    
    # Identity
    violation_id: str                       # Unique identifier
    
    # Violation details
    violation_kind: GovernanceFinding       # What was violated?
    affected_component: str                 # Which component failed?
    
    # Severity
    severity: str = "warning"               # "info", "warning", or "error"
    
    # Details
    description: str = ""                   # Human-readable explanation


@dataclass(frozen=True)
class GovernanceRecommendation:
    """
    A recommendation for improving probabilistic reasoning.
    
    Generated by governance evaluation to guide improvement.
    """
    
    # Identity
    recommendation_id: str                  # Unique identifier
    
    # Recommendation details
    issue_addressed: str                    # What does this fix?
    action_suggested: str                   # What should be done?
    priority: int = 1                       # Higher number = higher priority


@dataclass(frozen=True)
class ProbabilisticGovernance:
    """
    Governance evaluation for a probabilistic reasoning session.
    
    Evaluates:
        - Calibration quality
        - Distribution validity
        - Dependency consistency  
        - Uncertainty estimation
        - Fusion correctness
    
    Governance remains observational - it never modifies artifacts directly.
    """
    
    # Identity
    governance_id: str                      # Unique identifier
    
    # Evaluated sessions
    evaluated_sessions: Tuple[str, ...] = ()  # Which sessions were evaluated?
    
    # Findings
    findings: Tuple[GovernanceFinding, ...] = ()
    
    # Violations
    violations: Tuple[GovernanceViolation, ...] = ()
    
    # Recommendations
    recommendations: Tuple[GovernanceRecommendation, ...] = ()
    
    # Overall assessment
    is_compliant: bool = True               # All rules followed?
    
    # Metadata
    evaluated_at_utc: float = field(default_factory=time.time)
    
    @property
    def has_violations(self) -> bool:
        """Check if any violations were found."""
        return len(self.violations) > 0
    
    @property
    def violation_count(self) -> int:
        """Count number of violations by severity."""
        error_count = sum(1 for v in self.violations if v.severity == "error")
        warning_count = sum(1 for v in self.violations if v.severity == "warning")
        return error_count, warning_count
    
    @classmethod
    def create_compliant(cls, session_id: str) -> ProbabilisticGovernance:
        """Create a governance result showing compliance."""
        return cls(
            governance_id=f"governance:{uuid.uuid4().hex[:16]}",
            evaluated_sessions=(session_id,),
            findings=(),
            violations=(),
            recommendations=(),
            is_compliant=True,
        )
    
    @classmethod
    def create_noncompliant(
        cls,
        session_id: str,
        violation: GovernanceViolation,
    ) -> ProbabilisticGovernance:
        """Create a governance result showing non-compliance."""
        return cls(
            governance_id=f"governance:{uuid.uuid4().hex[:16]}",
            evaluated_sessions=(session_id,),
            findings=(),
            violations=(violation,),
            recommendations=(),
            is_compliant=False,
        )


def dataclass_replace(instance: Any, **kwargs: Any) -> Any:
    """Simple dataclass replace helper for frozen instances."""
    return instance.__class__(**{**instance.__dict__, **kwargs})


__all__ = [
    "ProbabilisticGovernance",
    "GovernanceFinding",
    "GovernanceViolation", 
    "GovernanceRecommendation",
]