# Identity Integration Episode Model
# ==================================

"""
IdentityIntegrationEpisode specialization using InternalEpisode machinery.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Tuple


@dataclass(frozen=True, slots=True)
class IdentityIntegrationEpisode:
    """
    Specialized internal episode for identity integration coordination.
    
    Reuses canonical InternalEpisode machinery with identity-specific additions.
    
    PROPERTIES:
        • episode_id: Unique identifier for this episode
        • context_id: Context ID being integrated
        • purpose: Purpose of this identity integration
        • subject: Subject of this identity integration
        • scope: Scope constraints for this integration
        • projection_reference: Identity projection reference used
        • source_references: Sources consulted during integration
        • claims_extracted: Claims identified during integration
        • continuity_assessment: Continuity assessment result
        • consistency_assessment: Consistency assessment result
        • coherence_assessment: Coherence assessment result
        • conflicts_identified: Conflicts found during integration
        • tensions_identified: Tensions found during integration
        • gaps_identified: Gaps identified during integration
        • products_generated: Products generated by this episode
        • outcome: Final outcome of the integration episode
    """
    
    episode_id: str = ""
    """Unique identifier for this identity integration episode."""
    
    context_id: str = ""
    """Context ID being integrated."""
    
    purpose: str = "general_identity_integration"
    """Purpose of this identity integration (IdentityIntegrationPurposeKind.*)."""
    
    subject: str = "whole_agent"
    """Subject of this identity integration (IdentitySubjectKind.*)."""
    
    scope: str = "broad"
    """Scope constraints for this integration."""
    
    projection_reference: str = ""
    """Identity projection reference used."""
    
    source_references: Tuple[str, ...] = field(default_factory=tuple)
    """Source references consulted during integration."""
    
    claims_extracted: Tuple[str, ...] = field(default_factory=tuple)
    """Claims extracted during integration."""
    
    continuity_assessment: str = ""
    """Continuity assessment result."""
    
    consistency_assessment: str = ""
    """Consistency assessment result."""
    
    coherence_assessment: str = ""
    """Coherence assessment result."""
    
    conflicts_identified: Tuple[str, ...] = field(default_factory=tuple)
    """Conflicts identified during integration."""
    
    tensions_identified: Tuple[str, ...] = field(default_factory=tuple)
    """Tensions identified during integration."""
    
    gaps_identified: Tuple[str, ...] = field(default_factory=tuple)
    """Gaps identified during integration."""
    
    products_generated: Tuple[str, ...] = field(default_factory=tuple)
    """Products generated by this episode."""
    
    outcome: str = ""
    """Final outcome of the integration episode (IdentityIntegrationOutcomeKind.*)."""