# Knowledge Audit Enums - Phase 6.10
# ===================================

"""
Enumerations for the Knowledge Audit subsystem.
"""

from __future__ import annotations

from enum import Enum, auto


# =============================================================================
# AUDIT DIMENSIONS - Independent audit engines
# =============================================================================

class AuditDimension(Enum):
    """
    Dimensions of knowledge audit that each have dedicated audit engines.
    
    Each dimension represents a different aspect of knowledge quality and validity.
    """
    
    # Core quality dimensions
    CONSISTENCY = "consistency"               # Internal logical consistency
    CONTRADICTION = "contradiction"           # Presence of contradictions
    REDUNDANCY = "redundancy"                 # Duplicate or redundant knowledge
    
    # Evidence and justification dimensions
    EVIDENCE = "evidence"                     # Quality and sufficiency of evidence
    PROVENANCE = "provenance"                 # Origin tracking and traceability
    
    # Temporal dimensions
    FRESHNESS = "freshness"                   # Temporal validity and currency
    
    # Structural dimensions
    COVERAGE = "coverage"                     # Completeness and scope
    DEPENDENCY = "dependency"                 # Dependency integrity
    USAGE = "usage"                           # Actual usage in reasoning
    
    # Cognitive dimensions
    APPlicability = "applicability"          # Applicability to current context
    CONFIDENCE = "confidence"                 # Confidence calibration
    UNCERTAINTY = "uncertainty"               # Uncertainty representation
    COMPLETENESS = "completeness"             # Completeness of information
    
    # Integrity dimensions
    INTEGRITY = "integrity"                   # Overall integrity and trustworthiness


# =============================================================================
# FINDING TYPES - Types of audit findings
# =============================================================================

class FindingType(Enum):
    """
    Types of audit findings that can be generated.
    
    Each finding type indicates a specific issue or observation about knowledge.
    """
    
    # Support status
    SUPPORTED = "supported"                   # Knowledge is supported by evidence
    UNSUPPORTED = "unsupported"               # No supporting evidence found
    
    # Contradiction types
    CONTRADICTED = "contradicted"             # Conflicting evidence exists
    LOW_CONFIDENCE = "low_confidence"         # Confidence below threshold
    OVERCONFIDENT = "overconfident"           # Confidence too high relative to evidence
    UNDERCONFIDENT = "underconfident"         # Confidence too low given evidence
    
    # Uncertainty types
    HIGH_UNCERTAINTY = "high_uncertainty"     # Uncertainty above acceptable level
    
    # Temporal types
    OBSOLETE = "obsolete"                     # Knowledge may be outdated
    TEMPORALLY_INVALID = "temporally_invalid"  # Knowledge no longer applicable
    
    # Structural types
    DUPLICATE = "duplicate"                   # Exact duplicate exists
    REDUNDANT = "redundant"                   # Partially redundant knowledge
    INCOMPLETE = "incomplete"                 # Missing important information
    
    # Provenance and evidence types
    POOR_PROVENANCE = "poor_provenance"       # Inadequate provenance tracking
    WEAK_EVIDENCE = "weak_evidence"           # Evidence quality is low
    
    # Usage and relevance types
    UNUSED = "unused"                         # Not used in reasoning
    SUPERSEDED = "superseded"                 # Replaced by newer knowledge
    LOW_COVERAGE = "low_coverage"             # Insufficient scope coverage
    
    # Dependency types
    BROKEN_DEPENDENCY = "broken_dependency"   # Referenced artifact missing
    CYCLIC_DEPENDENCY = "cyclic_dependency"   # Circular dependency detected
    
    # Conflict types
    WORLD_MODEL_CONFLICT = "world_model_conflict"  # Conflicts with world model
    SELF_MODEL_CONFLICT = "self_model_conflict"    # Conflicts with self model
    POLICY_CONFLICT = "policy_conflict"         # Violates constitutional knowledge


# =============================================================================
# RECOMMENDATION TYPES - Actions to address findings
# =============================================================================

class RecommendationType(Enum):
    """
    Types of recommendations generated by audit findings.
    
    Recommendations guide the next steps for addressing audit findings.
    They never directly modify knowledge; they are requests for action.
    """
    
    # Verification and validation
    VERIFY = "verify"                         # Verify this knowledge is correct
    REVALIDATE = "revalidate"                 # Revalidate with current evidence
    
    # Learning and refinement
    RELEARN = "relearn"                       # Learn from new evidence
    CONSOLIDATE = "consolidate"               # Consolidate similar knowledge
    MERGE = "merge"                           # Merge redundant knowledge
    SPLIT = "split"                           # Split complex knowledge
    
    # Deprecation and removal
    DEPRECATE = "deprecate"                   # Mark as deprecated
    ARCHIVE = "archive"                       # Archive for historical reference
    REMOVE = "remove"                         # Remove from active knowledge
    
    # Human involvement
    REQUEST_REFLECTION = "request_reflection"  # Request reflection on this
    REQUEST_LEARNING = "request_learning"     # Request learning intervention
    REQUEST_HUMAN_REVIEW = "request_human_review"  # Require human review
    
    # Model updates
    REQUEST_WORLD_MODEL_UPDATE = "request_world_model_update"
    REQUEST_SELF_MODEL_UPDATE = "request_self_model_update"


# =============================================================================
# AUDIT STATUS - Session and report states
# =============================================================================

class AuditStatus(Enum):
    """
    Status values for audit sessions and reports.
    """
    
    PENDING = "pending"                       # Audit not yet started
    RUNNING = "running"                       # Audit in progress
    COMPLETED = "completed"                   # Audit finished successfully
    FAILED = "failed"                         # Audit encountered error
    TIMEOUT = "timeout"                       # Audit exceeded timeout
    CANCELLED = "cancelled"                   # Audit was cancelled


# =============================================================================
# EVIDENCE QUALITY - Evidence assessment levels
# =============================================================================

class EvidenceQuality(Enum):
    """
    Quality levels for evidence supporting knowledge.
    """
    
    INVALID = "invalid"                       # No valid evidence
    WEAK = "weak"                             # Minimal or questionable evidence
    MODERATE = "moderate"                     # Some supporting evidence
    STRONG = "strong"                         # Well-supported by evidence
    CONCLUSIVE = "conclusive"                 # Evidence strongly supports claim


# =============================================================================
# CONFIDENCE CALIBRATION - Confidence assessment levels
# =============================================================================

class ConfidenceCalibration(Enum):
    """
    Calibration levels for confidence values.
    """
    
    UNCALIBRATED = "uncalibrated"             # No calibration applied
    UNDERCONFIDENT = "underconfident"         # Confidence too low
    CALIBRATED = "calibrated"                 # Properly calibrated
    OVERCONFIDENT = "overconfident"           # Confidence too high


# =============================================================================
# DEPENDENCY STATUS - Dependency evaluation states
# =============================================================================

class DependencyStatus(Enum):
    """
    Status of dependency relationships.
    """
    
    SATISFIED = "satisfied"                   # All dependencies met
    VIOLATED = "violated"                     # Dependencies violated
    MISSING = "missing"                       # Referenced artifact missing
    CIRCULAR = "circular"                     # Circular dependency detected


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    "AuditDimension",
    "FindingType",
    "RecommendationType",
    "AuditStatus",
    "EvidenceQuality",
    "ConfidenceCalibration",
    "DependencyStatus",
]