"""Architecture Report Manager.

Generates reports from architectural inventory data.
"""

import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .inventory import (
    ArchitectureInventory,
    PackageMetadata,
    ModuleMetadata,
    APIItem,
    RuntimeAuthority,
)


class ArchitectureReportManager:
    """
    Generates reports from architecture discovery results.
    
    Produces immutable reports including:
    - Architecture Inventory
    - Package Inventory  
    - Module Inventory
    - Authority Inventory
    - Runtime Object Inventory
    - Dependency Graph
    - Import Graph
    - Entry Point Inventory
    - Runtime Topology
    - Metrics Summary
    
    Supports Markdown and JSON output formats.
    """
    
    def __init__(self) -> None:
        """Initialize the report manager."""
        self._report_cache: Dict[str, str] = {}
    
    def generate_markdown_report(
        self,
        inventory: ArchitectureInventory
    ) -> str:
        """
        Generate a complete Markdown report from inventory.
        
        Args:
            inventory: The architecture inventory
            
        Returns:
            Markdown report string
        """
        sections = [
            "# Gordon Core - Architecture Inventory Report",
            "",
            f"**Repository**: {inventory.repository_path}",
            f"**Discovered At**: {self._format_timestamp(inventory.discovered_at)}",
            f"**Version**: {inventory.version}",
            "",
            "---",
            self._generate_summary_section(inventory),
            self._generate_packages_section(inventory),
            self._generate_modules_section(inventory),
            self._generate_authorities_section(inventory),
            self._generate_dependencies_section(inventory),
            self._generate_import_graph_section(inventory),
            self._generate_topology_section(inventory),
            self._generate_metrics_section(inventory),
            "",
            "---",
            "*Generated by Architecture Report Manager v1.0.0*"
        ]
        
        return "\n".join(sections)
    
    def generate_json_report(
        self,
        inventory: ArchitectureInventory
    ) -> str:
        """
        Generate a JSON report from inventory.
        
        Args:
            inventory: The architecture inventory
            
        Returns:
            JSON report string
        """
        report = {
            "repository_path": inventory.repository_path,
            "discovered_at": inventory.discovered_at,
            "version": inventory.version,
            "packages": self._serialize_packages(inventory.packages),
            "modules": self._serialize_modules(inventory.modules),
            "public_apis": self._serialize_apis(inventory.public_apis),
            "runtime_authorities": self._serialize_authorities(inventory.runtime_authorities),
            "topology_nodes": [self._node_to_dict(n) for n in inventory.topology_nodes],
            "metrics": {
                "total_packages": inventory.total_packages,
                "total_modules": inventory.total_modules,
                "total_classes": inventory.total_classes,
                "total_functions": inventory.total_functions,
                "total_protocols": inventory.total_protocols,
                "total_dataclasses": inventory.total_dataclasses,
                "total_enums": inventory.total_enums,
                "total_authorities": inventory.total_authorities,
            }
        }
        
        return json.dumps(report, indent=2)
    
    def _serialize_packages(self, packages: Tuple[PackageMetadata, ...]) -> List[Dict]:
        """Serialize packages to dictionary list."""
        result = []
        for pkg in packages:
            result.append({
                "name": pkg.name,
                "path": pkg.path,
                "owner": pkg.owner,
                "category": pkg.category.value,
                "layer": pkg.layer,
                "version": pkg.version,
                "stability": pkg.stability,
                "lifecycle_participation": pkg.lifecycle_participation.value
            })
        return result
    
    def _serialize_modules(self, modules: Tuple[ModuleMetadata, ...]) -> List[Dict]:
        """Serialize modules to dictionary list."""
        result = []
        for mod in modules:
            result.append({
                "name": mod.name,
                "path": mod.path,
                "package_name": mod.package_name,
                "lifecycle_participation": mod.lifecycle_participation.value
            })
        return result
    
    def _serialize_apis(self, apis: Tuple[APIItem, ...]) -> List[Dict]:
        """Serialize API items to dictionary list."""
        result = []
        for api in apis:
            result.append({
                "name": api.name,
                "type": api.type_.value,
                "defining_package": api.defining_package
            })
        return result
    
    def _serialize_authorities(self, authorities: Tuple[RuntimeAuthority, ...]) -> List[Dict]:
        """Serialize authorities to dictionary list."""
        result = []
        for auth in authorities:
            result.append({
                "name": auth.name,
                "category": auth.category,
                "implementation": auth.implementation,
                "owner": auth.owner
            })
        return result
    
    def _node_to_dict(self, node) -> Dict:
        """Convert a TopologyNode to dictionary."""
        return {
            "id": node.id,
            "name": node.name,
            "category": node.category,
            "type_": node.type_,
            "owner": node.owner
        }
    
    def _format_timestamp(self, timestamp: float) -> str:
        """Format a timestamp for display."""
        import time
        return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp))
    
    def generate_mermaid_package_hierarchy(
        self,
        packages: Tuple[PackageMetadata, ...]
    ) -> str:
        """Generate Mermaid diagram for package hierarchy."""
        lines = [
            "```mermaid",
            "flowchart TD",
            "    subgraph Core [Core Packages]",
            "        direction TB"
        ]
        
        core_pkgs = [p for p in packages if p.category.value == "core"]
        for pkg in core_pkgs:
            lines.append(f"        {pkg.name}[{pkg.name}]")
        
        lines.extend([
            "    end",
            "",
            "    subgraph Kernel [Kernel Packages]",
            "        direction TB"
        ])
        
        kernel_pkgs = [p for p in packages if p.category.value == "kernel"]
        for pkg in kernel_pkgs:
            lines.append(f"        {pkg.name}[{pkg.name}]")
        
        lines.extend([
            "    end",
            "",
            "    subgraph Runtime [Runtime Packages]",
            "        direction TB"
        ])
        
        runtime_pkgs = [p for p in packages if p.category.value == "runtime"]
        for pkg in runtime_pkgs:
            lines.append(f"        {pkg.name}[{pkg.name}]")
        
        lines.extend([
            "    end",
            "",
            "    subgraph Execution [Execution Packages]",
            "        direction TB"
        ])
        
        exec_pkgs = [p for p in packages if p.category.value == "execution"]
        for pkg in exec_pkgs:
            lines.append(f"        {pkg.name}[{pkg.name}]")
        
        lines.extend([
            "    end",
            "```"
        ])
        
        return "\n".join(lines)
    
    def generate_mermaid_dependency_graph(
        self,
        edges,  # Tuple of DependencyEdge or ImportEdge
    ) -> str:
        """Generate Mermaid diagram for dependency graph."""
        lines = [
            "```mermaid",
            "flowchart LR"
        ]
        
        seen_nodes = set()
        for edge in edges:
            from_node = self._sanitize_mermaid_id(str(edge.from_entity))
            to_node = self._sanitize_mermaid_id(str(edge.to_entity))
            
            if from_node not in seen_nodes:
                lines.append(f"    {from_node}[{edge.from_entity}]")
                seen_nodes.add(from_node)
            
            if to_node not in seen_nodes:
                lines.append(f"    {to_node}[{edge.to_entity}]")
                seen_nodes.add(to_node)
            
            lines.append(f"    {from_node} -->|{getattr(edge, 'type_', 'depends')}| {to_node}")
        
        lines.append("```")
        
        return "\n".join(lines)
    
    def _sanitize_mermaid_id(self, id_str: str) -> str:
        """Sanitize an ID for use in Mermaid diagrams."""
        # Replace special characters with underscores
        import re
        return re.sub(r"[^a-zA-Z0-9_]", "_", id_str)
    
    def _generate_summary_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the executive summary section."""
        return "\n".join([
            "## Executive Summary",
            "",
            f"This report provides a complete architectural inventory of the Gordon Core "
            f"runtime as discovered from `{inventory.repository_path}`.",
            "",
            "| Metric | Count |",
            "|--------|-------|",
            f"| Total Packages | {inventory.total_packages} |",
            f"| Total Modules | {inventory.total_modules} |",
            f"| Total Classes | {inventory.total_classes} |",
            f"| Total Functions | {inventory.total_functions} |",
            f"| Runtime Authorities | {inventory.total_authorities} |",
            ""
        ])
    
    def _generate_packages_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the packages section."""
        lines = [
            "## Package Inventory",
            "",
            "| Name | Path | Category | Layer | Owner |",
            "|------|------|----------|-------|-------|"
        ]
        
        for pkg in sorted(inventory.packages, key=lambda p: p.name):
            lines.append(
                f"| {pkg.name} | `{pkg.path}` | {pkg.category.value} | "
                f"{pkg.layer} | {pkg.owner} |"
            )
        
        return "\n".join(lines)
    
    def _generate_modules_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the modules section."""
        lines = [
            "## Module Inventory",
            "",
            "| Package | Module | Path | Lifecycle Participation |",
            "|---------|--------|------|------------------------|"
        ]
        
        for mod in sorted(inventory.modules, key=lambda m: (m.package_name, m.name)):
            lines.append(
                f"| {mod.package_name} | {mod.name} | `{mod.path}` | "
                f"{mod.lifecycle_participation.value} |"
            )
        
        return "\n".join(lines)
    
    def _generate_authorities_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the authorities section."""
        lines = [
            "## Runtime Authority Inventory",
            "",
            "| Name | Category | Implementation | Owner | Scope |",
            "|------|----------|----------------|-------|-------|"
        ]
        
        for auth in sorted(inventory.runtime_authorities, key=lambda a: a.name):
            lines.append(
                f"| {auth.name} | {auth.category} | `{auth.implementation}` | "
                f"{auth.owner} | {auth.scope} |"
            )
        
        return "\n".join(lines)
    
    def _generate_dependencies_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the dependencies section."""
        lines = [
            "## Dependency Graph",
            "",
            "### Package Dependencies",
            "",
            "| From | To | Type | Required |",
            "|------|----|------|----------|"
        ]
        
        # Convert package dependencies to displayable format
        for edge in inventory.package_dependencies.edges:
            lines.append(
                f"| {edge.from_entity} | {edge.to_entity} | {edge.type_} | "
                f"{'Yes' if edge.required else 'No'} |"
            )
        
        return "\n".join(lines)
    
    def _generate_import_graph_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the import graph section."""
        lines = [
            "## Import Graph",
            "",
            "| From Module | To Module | Type |",
            "|-------------|-----------|------|"
        ]
        
        for edge in inventory.import_graph_edges:
            lines.append(f"| {edge.from_module} | {edge.to_module} | {edge.type_} |")
        
        return "\n".join(lines)
    
    def _generate_topology_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the topology section."""
        lines = [
            "## Runtime Topology",
            "",
            "| ID | Name | Category | Type | Owner | Scope |",
            "|----|------|----------|------|-------|-------|"
        ]
        
        for node in sorted(inventory.topology_nodes, key=lambda n: (n.category, n.name)):
            lines.append(
                f"| {node.id} | {node.name} | {node.category} | "
                f"{node.type_} | {node.owner or 'N/A'} | {node.scope} |"
            )
        
        return "\n".join(lines)
    
    def _generate_metrics_section(self, inventory: ArchitectureInventory) -> str:
        """Generate the metrics section."""
        return "\n".join([
            "## Metrics Summary",
            "",
            "| Metric | Count |",
            "|--------|-------|",
            f"| Total Packages | {inventory.total_packages} |",
            f"| Total Modules | {inventory.total_modules} |",
            f"| Total Classes | {inventory.total_classes} |",
            f"| Total Functions | {inventory.total_functions} |",
            f"| Total Protocols | {inventory.total_protocols} |",
            f"| Total Dataclasses | {inventory.total_dataclasses} |",
            f"| Total Enums | {inventory.total_enums} |",
            f"| Total Authorities | {inventory.total_authorities} |",
            ""
        ])