# World-Model Reasoning - Phase 7.44
# ==================================

"""
World-Model Reasoning provides Gordon's environment intelligence architecture.

It maintains a persistent, causally consistent representation of the external world.
"""

from .shared import (
    WorldDescriptor,
    WorldKind,
    WorldState,
    WorldSet,
    WorldPipeline,
    EntityIdentity,
    EntityState,
    EntityRelationship,
    EntityAnalysis,
    EntityManagement,
    SceneRegion,
    SceneObject,
    SceneTopologyGraph,
    SceneAnalysis,
    SceneManagement,
    StateTransition,
    MotionTrack,
    CausalTransition,
    WorldDynamics,
    WorldDynamicsManagement,
    ConsistencyKind,
    ConsistencyState,
    ConsistencyViolation,
    ConsistencyMetric,
    WorldConsistency,
    WorldConsistencyManagement,
    EvolutionTrigger,
    WorldRevision,
    WorldEvolution,
    ValidationKind,
    ValidationState,
    ValidationResult,
    WorldValidation,
    FailureKind,
    WorldFailure,
    GovernanceFinding,
    WorldGovernance,
    HealthMetric,
    WorldHealth,
    DiagnosticEvent,
    WorldDiagnostics,
)

__all__ = [
    "WorldDescriptor",
    "WorldKind",
    "WorldState",
    "WorldSet",
    "WorldPipeline",
    "EntityIdentity",
    "EntityState",
    "EntityRelationship",
    "EntityAnalysis",
    "EntityManagement",
    "SceneRegion",
    "SceneObject",
    "SceneTopologyGraph",
    "SceneAnalysis",
    "SceneManagement",
    "StateTransition",
    "MotionTrack",
    "CausalTransition",
    "WorldDynamics",
    "WorldDynamicsManagement",
    "ConsistencyKind",
    "ConsistencyState",
    "ConsistencyViolation",
    "ConsistencyMetric",
    "WorldConsistency",
    "WorldConsistencyManagement",
    "EvolutionTrigger",
    "WorldRevision",
    "WorldEvolution",
    "ValidationKind",
    "ValidationState",
    "ValidationResult",
    "WorldValidation",
    "FailureKind",
    "WorldFailure",
    "GovernanceFinding",
    "WorldGovernance",
    "HealthMetric",
    "WorldHealth",
    "DiagnosticEvent",
    "WorldDiagnostics",
]