# Knowledge Identity - Phase 6.1
# ==============================

"""
Knowledge Identity: Semantic identity management in Gordon's knowledge system.

Semantic identity is the unique, stable identifier that distinguishes one
semantic artifact from another. It is independent of content and persists
through revisions, providing a consistent reference point.

Key Principles:
    - Identity is immutable once assigned
    - Identity is distinct from content
    - Identity enables revision tracking
    - Identity supports provenance tracking
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any
from enum import Enum, auto
import time
import uuid


# =============================================================================
# IDENTITY SOURCES - Where identities originate
# =============================================================================


class IdentitySource(Enum):
    """
    Sources of semantic identity assignment.
    
    Defines the origin mechanism for semantic identifiers in Gordon's knowledge system.
    """
    
    SYSTEM_GENERATED = "system_generated"   # Auto-generated by knowledge engine
    EXTERNAL_SOURCE = "external_source"     # Imported from external source
    USER_DEFINED = "user_defined"           # Explicitly provided by user
    DERIVED = "derived"                     # Computed from content hash
    
    UNKNOWN = "unknown"


# =============================================================================
# IDENTITY RESOLUTION - Finding identities in the system
# =============================================================================


class IdentityResolution(Enum):
    """
    Methods for resolving semantic identity conflicts.
    
    Defines how Gordon handles situations where multiple identities claim
    to represent the same semantic artifact.
    """
    
    FIRST_WINS = "first_wins"               # First identity accepted
    HIGHEST_AUTHORITY = "highest_authority" # Highest authority identity wins
    MERGE = "merge"                         # Merge into unified identity
    CONFLICT = "conflict"                   # Mark as unresolved conflict
    
    UNKNOWN = "unknown"


# =============================================================================
# SEMANTIC IDENTITY - Core identity representation
# =============================================================================


@dataclass(frozen=True)
class SemanticIdentity:
    """
    Semantic identity for knowledge artifacts.
    
    Provides a stable, unique identifier that persists through revisions
    and content changes. The identity is independent of the semantic
    content itself.
    
    Fields:
        identity:           The unique identifier string
        identity_type:      Category of this identity (concept, assertion, etc.)
        source:             Origin mechanism for this identity
        assigned_at_utc:    When the identity was first assigned
        metadata:           Additional identity information
    """
    
    # Identity core (required)
    identity: str                       # Unique identifier string
    
    # Identity classification
    identity_type: str = "unknown"      # e.g., "concept", "assertion", "relation"
    
    # Origin tracking
    source: IdentitySource = IdentitySource.SYSTEM_GENERATED
    assigned_at_utc: float = field(default_factory=time.time)
    
    # Metadata
    namespace: Optional[str] = None     # Optional namespace qualifier
    metadata: Dict[str, Any] = field(default_factory=dict)  # Additional data
    
    @property
    def is_valid(self) -> bool:
        """Check if identity has valid data."""
        return len(self.identity) > 0 and self.source != IdentitySource.UNKNOWN
    
    @classmethod
    def generate(
        cls,
        identity_type: str = "unknown",
        namespace: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> "SemanticIdentity":
        """
        Generate a new system-assigned semantic identity.
        
        Args:
            identity_type: Category of artifact being identified
            namespace: Optional namespace qualifier
            metadata: Additional identity information
            
        Returns:
            New SemanticIdentity with unique identifier
        """
        return cls(
            identity=f"sid:{uuid.uuid4().hex[:24]}",
            identity_type=identity_type,
            source=IdentitySource.SYSTEM_GENERATED,
            assigned_at_utc=time.time(),
            namespace=namespace,
            metadata=metadata or {},
        )
    
    @classmethod
    def from_external(
        cls,
        external_id: str,
        identity_type: str = "unknown",
        source_name: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> "SemanticIdentity":
        """
        Create an identity for externally sourced content.
        
        Args:
            external_id: The original identifier from external source
            identity_type: Category of artifact being identified
            source_name: Name of the external source
            metadata: Additional identity information
        """
        return cls(
            identity=f"ext:{source_name or 'unknown'}:{external_id}"[:64],
            identity_type=identity_type,
            source=IdentitySource.EXTERNAL_SOURCE,
            assigned_at_utc=time.time(),
            metadata={
                **(metadata or {}),
                "external_origin": external_id,
                "source_name": source_name,
            },
        )
    
    @classmethod
    def from_hash(
        cls,
        content: str,
        identity_type: str = "unknown",
        namespace: Optional[str] = None,
    ) -> "SemanticIdentity":
        """
        Create an identity derived from content hash.
        
        This enables content-addressable identities that are deterministic.
        
        Args:
            content: Content to derive identity from
            identity_type: Category of artifact being identified
            namespace: Optional namespace qualifier
        """
        import hashlib
        content_hash = hashlib.sha256(content.encode()).hexdigest()[:16]
        return cls(
            identity=f"hash:{content_hash}",
            identity_type=identity_type,
            source=IdentitySource.DERIVED,
            assigned_at_utc=time.time(),
            namespace=namespace,
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert identity to dictionary for serialization."""
        return {
            "identity": self.identity,
            "identity_type": self.identity_type,
            "source": self.source.value,
            "assigned_at_utc": self.assigned_at_utc,
            "namespace": self.namespace,
            "metadata": dict(self.metadata),
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SemanticIdentity":
        """Create identity from dictionary."""
        return cls(
            identity=data.get("identity", ""),
            identity_type=data.get("identity_type", "unknown"),
            source=IdentitySource(data.get("source", "unknown")),
            assigned_at_utc=float(data.get("assigned_at_utc", time.time())),
            namespace=data.get("namespace"),
            metadata=dict(data.get("metadata", {})),
        )


# =============================================================================
# IDENTITY TRACKER - Manage identities across revisions
# =============================================================================


class IdentityTracker:
    """
    Tracks semantic identity across all revisions of an artifact.
    
    Maintains a complete history of identity assignments and resolutions,
    providing auditability of the entire revision chain.
    """
    
    def __init__(self, initial_identity: SemanticIdentity):
        """
        Initialize the identity tracker.
        
        Args:
            initial_identity: The first identity in the revision chain
        """
        self._current_identity = initial_identity
        self._revision_history: List[Tuple[SemanticIdentity, float]] = [
            (initial_identity, time.time())
        ]
    
    @property
    def current_identity(self) -> SemanticIdentity:
        """Get the current active identity."""
        return self._current_identity
    
    @property
    def revision_count(self) -> int:
        """Get total number of revisions tracked."""
        return len(self._revision_history)
    
    def track_revision(
        self,
        new_identity: Optional[SemanticIdentity] = None,
    ) -> SemanticIdentity:
        """
        Track a new revision with optional identity change.
        
        Args:
            new_identity: Optional new identity for this revision
            
        Returns:
            The identity after tracking
        """
        timestamp = time.time()
        if new_identity is None:
            # Identity stays the same across revisions
            tracked_identity = self._current_identity
        else:
            # New identity assigned (e.g., after merge)
            tracked_identity = new_identity
        
        self._revision_history.append((tracked_identity, timestamp))
        self._current_identity = tracked_identity
        
        return tracked_identity
    
    def get_revision(self, revision_number: int) -> Optional[SemanticIdentity]:
        """
        Get the identity at a specific revision number.
        
        Args:
            revision_number: 1-indexed revision number
            
        Returns:
            Identity at that revision, or None if invalid
        """
        if 0 < revision_number <= len(self._revision_history):
            return self._revision_history[revision_number - 1][0]
        return None
    
    def get_all_identities(self) -> List[Tuple[SemanticIdentity, float]]:
        """Get all identities in history with timestamps."""
        return list(self._revision_history)


# =============================================================================
# IDENTITY VALIDATOR
# =============================================================================


class IdentityValidator:
    """
    Validates semantic identity assignments.
    
    Ensures identity uniqueness and consistency across the knowledge system.
    """
    
    def __init__(
        self,
        require_namespace: bool = False,
        min_length: int = 8,
        max_length: int = 256,
    ):
        """
        Initialize the validator.
        
        Args:
            require_namespace: Whether identities must include namespace
            min_length: Minimum identity string length
            max_length: Maximum identity string length
        """
        self._require_namespace = require_namespace
        self._min_length = min_length
        self._max_length = max_length
    
    def validate(self, identity: SemanticIdentity) -> Tuple[bool, List[str]]:
        """
        Validate a semantic identity.
        
        Args:
            identity: Identity to validate
            
        Returns:
            (is_valid, list_of_issues)
        """
        issues = []
        
        # Rule 1: Must have non-empty identity
        if not identity.identity or len(identity.identity) == 0:
            issues.append("Empty identity")
        
        # Rule 2: Length constraints
        if len(identity.identity) < self._min_length:
            issues.append(f"Identity too short (min: {self._min_length})")
        
        if len(identity.identity) > self._max_length:
            issues.append(f"Identity too long (max: {self._max_length})")
        
        # Rule 3: Namespace requirement
        if self._require_namespace and not identity.namespace:
            issues.append("Missing required namespace")
        
        # Rule 4: Source must be known
        if identity.source == IdentitySource.UNKNOWN:
            issues.append("Unknown identity source")
        
        return len(issues) == 0, issues


__all__ = [
    "IdentitySource",
    "IdentityResolution",
    "SemanticIdentity",
    "IdentityTracker",
    "IdentityValidator",
]