# Alerting Network Enums
# ========================

"""
Alerting-specific enumerations.

These define bounded categorical types used throughout the AlertingNetwork.
All enums are immutable and hashable for deterministic behavior.
"""

from enum import Enum, auto
from typing import FrozenSet


class AlertingModality(Enum):
    """
    Signal modality or sensory channel.
    
    Represents the type of signal being assessed. Does not imply any specific
    implementation (vision, hearing, etc.) - those belong to Perception or
    later implementation layers.
    """
    
    VISUAL = "visual"
    AUDITORY = "auditory"
    TACTILE = "tactile"
    OLFATORY = "olfactory"
    GUSTATORY = "gustatory"
    INTEROCEPTIVE = "interoceptive"
    COGNITIVE = "cognitive"
    EMOTIONAL = "emotional"
    
    # Generic / unknown modalities
    GENERIC = "generic"
    UNKNOWN = "unknown"
    
    def is_known(self) -> bool:
        """Return True if modality is not UNKNOWN or GENERIC."""
        return self not in (AlertingModality.UNKNOWN, AlertingModality.GENERIC)


class AlertingSource(Enum):
    """
    Origin of the signal.
    
    Indicates where the signal came from without embedding implementation
    details. Source identity belongs to higher layers (Perception, Memory, etc.)
    """
    
    # Exogenous sources (external)
    PERCEPTION = "perception"  # Sensory input via Perception systems
    ENVIRONMENT = "environment"  # External environmental signals
    
    # Endogenous sources (internal)
    MEMORY = "memory"  # Retrieved from memory systems
    COGNITION = "cognition"  # Generated by cognitive processes
    EMOTION = "emotion"  # Generated by affective systems
    EXECUTION = "execution"  # Generated during task execution
    
    # System-generated sources
    INTERNAL_MONITOR = "internal_monitor"
    METACOGNITION = "metacognition"
    
    # Generic / unknown
    GENERIC = "generic"
    UNKNOWN = "unknown"
    
    def is_exogenous(self) -> bool:
        """Return True if source is external to the agent."""
        return self in (AlertingSource.PERCEPTION, AlertingSource.ENVIRONMENT)
    
    def is_endogenous(self) -> bool:
        """Return True if source is generated internally."""
        return self in (
            AlertingSource.MEMORY,
            AlertingSource.COGNITION,
            AlertingSource.EMOTION,
            AlertingSource.EXECUTION,
            AlertingSource.INTERNAL_MONITOR,
            AlertingSource.METACOGNITION,
        )


class AlertingLevel(Enum):
    """
    Bounded alert demand classification.
    
    Describes the strength of attention demand. Does NOT authorize behavior.
    
    Levels:
        NEGLIGIBLE: Signal is below baseline threshold, no attention required
        LOW: Minor deviation from baseline, observation sufficient
        MODERATE: Noticeable deviation, consider attention allocation
        HIGH: Significant deviation, allocate attention soon
        CRITICAL: Extreme deviation, demand immediate attention review
    """
    
    NEGLIGIBLE = "negligible"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"
    
    @classmethod
    def from_score(cls, score: float) -> "AlertingLevel":
        """
        Infer level from a demand score.
        
        This is a convenience method for testing or debugging.
        The actual assessment comes from configuration-defined thresholds.
        """
        if score < 0.1:
            return cls.NEGLIGIBLE
        elif score < 0.3:
            return cls.LOW
        elif score < 0.5:
            return cls.MODERATE
        elif score < 0.8:
            return cls.HIGH
        else:
            return cls.CRITICAL
    
    def requires_attention(self) -> bool:
        """Return True if this level warrants attention review."""
        return self in (AlertingLevel.LOW, AlertingLevel.MODERATE, 
                       AlertingLevel.HIGH, AlertingLevel.CRITICAL)


class AlertingRecommendation(Enum):
    """
    Advisory recommendation for attention handling.
    
    These are recommendations only. They do NOT command behavior.
    Consumers decide whether and how to act on recommendations.
    
    Values:
        IGNORE: No attention needed; signal is below threshold
        OBSERVE: Monitor the signal, no action required yet
        ELEVATE: Signal deserves elevated priority in attention allocation
        REQUEST_ATTENTION: Allocate some attention resources to this signal
        REQUEST_URGENT_ATTENTION: Signal demands immediate attention review
    """
    
    IGNORE = "ignore"
    OBSERVE = "observe"
    ELEVATE = "elevate"
    REQUEST_ATTENTION = "request_attention"
    REQUEST_URGENT_ATTENTION = "request_urgent_attention"
    
    @property
    def is_advisory(self) -> bool:
        """All recommendations are advisory by design."""
        return True


class AlertingReasonCategory(Enum):
    """
    Categories for alert reasons.
    
    Used to classify why a signal generated particular attention demand.
    Each reason must correspond to actual computed evidence, not fixed text.
    """
    
    # Temporal changes
    SUDDEN_INTENSITY_CHANGE = "sudden_intensity_change"
    UNEXPECTED_ONSET = "unexpected_onset"
    UNEXPECTED_OFFSET = "unexpected_offset"
    PATTERN_VIOLATION = "pattern_violation"
    
    # Novelty-related
    NOVELTY = "novelty"
    NEW_SOURCE = "new_source"
    DISTRIBUTION_SHIFT = "distribution_shift"
    
    # Prediction and error
    PREDICTION_ERROR = "prediction_error"
    EXPECTATION_VIOLATION = "expectation_violation"
    
    # Urgency factors
    URGENCY = "urgency"
    RAPID_CHANGE = "rapid_change"
    THRESHOLD_CROSSING = "threshold_crossing"
    
    # Contrast and salience
    HIGH_CONTRAST = "high_contrast"
    RELATIVE_INTENSITY = "relative_intensity"
    
    # Biological relevance (if enabled)
    BIOLOGICAL_RELEVANCE = "biological_relevance"
    SURVIVAL_RELEVANCE = "survival_relevance"
    
    # Contextual modulation
    CONTEXTUAL_RELEVANCE = "contextual_relevance"
    TASK_CRITICALITY_RESPONSE = "task_criticality_response"
    
    # State-based attenuation
    LOW_HABITUATION = "low_habituation"
    REFRACTORY_SUPPRESSION = "refractory_suppression"


class AlertingStateTransition(Enum):
    """
    Bounded state transition type for a signal.
    
    Describes how the internal state evolved during assessment.
    Used for explainability and debugging, not behavioral control.
    """
    
    NEW_SIGNAL = "new_signal"  # First observation of this signal
    BASELINE_UPDATE = "baseline_update"  # Updated baseline statistics
    HABITUATION_CHANGE = "habituation_change"  # Habituation level changed
    REFRATORY_EXPIRED = "refractory_expired"  # Refractory period ended
    INTENSITY_SHIFT = "intensity_shift"  # Significant intensity change detected
    NOVELTY_DETECTED = "novelty_detected"  # Signal differs from baseline
    
    @property
    def is_state_change(self) -> bool:
        """Return True if this transition represents a state mutation."""
        return self != AlertingStateTransition.NEW_SIGNAL