# Reasoning Alternatives - Phase 7.0
# ====================================

"""
Canonical Alternative Contract.

Alternatives are candidate solutions or strategies under consideration.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any


@dataclass(frozen=True)
class ReasoningAlternative:
    """
    A candidate solution or strategy generated by reasoning.
    
    An alternative contains:
        - Identity and semantic tracking
        - Originating reasoning that produced it
        - Assumptions underlying the alternative
        - Expected outcomes if implemented
        - Provenance tracking
    
    Alternatives remain candidates until deliberated upon.
    """
    
    # Identity
    alternative_id: str                     # Unique identifier
    semantic_identity: str                  # Stable identity for comparison
    
    # Origin
    originating_reasoning: str              # Which reasoning produced this?
    
    # Content
    description: str                        # What is this alternative?
    category: str = "general"               # e.g., "repair", "strategy", "explanation"
    
    # Underlying assumptions
    supporting_assumptions: Tuple[str, ...] = ()  # What must be true for this to work?
    
    # Expected outcomes
    expected_outcomes: Tuple[str, ...] = ()   # What should happen if implemented?
    
    # Assessment (to be filled by deliberation)
    assessed_ranking: Optional[int] = None  # Position in ranking (1-based)
    assessed_score: Optional[float] = None  # Quality score (0.0-1.0)
    
    # Timing
    created_at_utc: float = field(default_factory=time.time)
    
    # Provenance
    provenance: Dict[str, str] = field(default_factory=dict)
    
    @property
    def assumption_count(self) -> int:
        """Count of supporting assumptions."""
        return len(self.supporting_assumptions)
    
    @classmethod
    def create(
        cls,
        description: str,
        originating_reasoning: str,
        category: str = "general",
        assumptions: Optional[List[str]] = None,
        expected_outcomes: Optional[List[str]] = None,
    ) -> ReasoningAlternative:
        """Create a new alternative."""
        return cls(
            alternative_id=f"alternative:{uuid.uuid4().hex[:16]}",
            semantic_identity=originating_reasoning + ":" + description,
            originating_reasoning=originating_reasoning,
            description=description,
            category=category,
            supporting_assumptions=tuple(assumptions or []),
            expected_outcomes=tuple(expected_outcomes or []),
        )


@dataclass(frozen=True)
class AlternativeComparison:
    """
    Comparison of multiple alternatives.
    
    A comparison documents how alternatives were evaluated relative to each other.
    """
    
    # Identity
    comparison_id: str                      # Unique identifier
    
    # Alternatives compared
    compared_alternative_ids: Tuple[str, ...]  # All alternatives in comparison
    
    # Evaluation criteria
    criteria: Dict[str, float] = field(default_factory=dict)  # criterion_name -> weight
    
    # Results per alternative
    scores_by_alternative: Dict[str, float] = field(default_factory=dict)  # alt_id -> score
    
    # Ranking result
    ranked_alternatives: Tuple[Tuple[str, int], ...] = ()  # (alt_id, rank) pairs
    
    # Selected winner
    selected_alternative: Optional[str] = None              # Winner if any
    
    # Timing
    compared_at_utc: float = field(default_factory=time.time)
    
    @property
    def is_decided(self) -> bool:
        """Check if a winner was selected."""
        return self.selected_alternative is not None
    
    @classmethod
    def create(
        cls,
        alternative_ids: List[str],
        criteria: Optional[Dict[str, float]] = None,
    ) -> AlternativeComparison:
        """Create a new comparison."""
        return cls(
            comparison_id=f"comparison:{uuid.uuid4().hex[:16]}",
            compared_alternative_ids=tuple(alternative_ids),
            criteria=criteria or {},
            scores_by_alternative={},
            ranked_alternatives=(),
        )


@dataclass(frozen=True)
class AlternativeRanking:
    """
    Ranking of alternatives by quality or preference.
    
    A ranking preserves the order of alternatives and may include
    scores, ties, and uncertainty about ordering.
    """
    
    # Identity
    ranking_id: str                         # Unique identifier
    
    # Alternatives in order (first = best)
    ranked_alternative_ids: Tuple[str, ...]  # Ordered list of alt IDs
    
    # Scores if available
    scores_by_alternative: Dict[str, float] = field(default_factory=dict)
    
    # Uncertainty about ranking
    ranking_confidence: float = 0.5         # How confident in the ordering?
    
    # Ties (groups of alternatives that are equivalent)
    equivalence_classes: Tuple[Tuple[str, ...], ...] = ()  # Each tuple is a tie group
    
    # Timing
    ranked_at_utc: float = field(default_factory=time.time)
    
    @property
    def best_alternative(self) -> Optional[str]:
        """Get the top-ranked alternative."""
        return self.ranked_alternative_ids[0] if self.ranked_alternative_ids else None
    
    @property
    def ranking_size(self) -> int:
        """Count of alternatives ranked."""
        return len(self.ranked_alternative_ids)
    
    @classmethod
    def create(
        cls,
        alternative_ids: List[str],
        scores: Optional[Dict[str, float]] = None,
    ) -> AlternativeRanking:
        """Create a new ranking from scored alternatives."""
        # Sort by score descending
        sorted_ids = sorted(
            alternative_ids,
            key=lambda aid: (scores or {}).get(aid, 0.5),
            reverse=True
        )
        
        return cls(
            ranking_id=f"ranking:{uuid.uuid4().hex[:16]}",
            ranked_alternative_ids=tuple(sorted_ids),
            scores_by_alternative=scores or {},
        )


__all__ = [
    "ReasoningAlternative", 
    "AlternativeComparison", 
    "AlternativeRanking",
]