# Reasoning Hypothesis - Phase 7.0
# ==================================

"""
Canonical Hypothesis Contract.

Hypotheses are candidate explanations that remain under evaluation.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional, Any


@dataclass(frozen=True)
class ReasoningHypothesis:
    """
    A candidate explanation generated by reasoning.
    
    A hypothesis contains:
        - Identity and semantic tracking
        - Supporting artifacts (evidence, observations)
        - Contradicting artifacts (known conflicts)
        - Confidence level (0.0-1.0)
        - Uncertainty measures
        - Provenance
    
    Hypotheses remain candidates until evaluated.
    They never become beliefs automatically.
    """
    
    # Identity
    hypothesis_id: str                      # Unique identifier
    semantic_identity: str                  # Stable identity for comparison
    
    # Content
    explanation: str                        # The proposed explanation
    context: Tuple[str, ...] = ()           # Context where this applies
    
    # Evidence
    supporting_artifacts: Tuple[str, ...]   # Supporting evidence references
    contradicting_artifacts: Tuple[str, ...] = ()  # Contradicting evidence
    
    # Assessment
    confidence: float = 0.5                 # Confidence in hypothesis (0.0-1.0)
    uncertainty: float = 0.3                # Remaining uncertainty
    
    # Metadata
    created_at_utc: float = field(default_factory=time.time)
    expires_at_utc: Optional[float] = None  # Optional expiration time
    
    # Provenance
    generated_by: str = "unknown"           # Which inference produced this?
    provenance: Dict[str, str] = field(default_factory=dict)
    
    @property
    def is_expired(self) -> bool:
        """Check if hypothesis has expired."""
        if self.expires_at_utc is None:
            return False
        return time.time() > self.expires_at_utc
    
    @property
    def evidence_ratio(self) -> float:
        """Ratio of supporting to total evidence."""
        total = len(self.supporting_artifacts) + len(self.contradicting_artifacts)
        if total == 0:
            return 0.5
        return len(self.supporting_artifacts) / total
    
    @classmethod
    def create(
        cls,
        explanation: str,
        semantic_identity: str,
        supporting_evidence: List[str],
        contradicting_evidence: Optional[List[str]] = None,
        confidence: float = 0.5,
        uncertainty: float = 0.3,
        generated_by: str = "unknown",
    ) -> ReasoningHypothesis:
        """Create a new hypothesis."""
        return cls(
            hypothesis_id=f"hypothesis:{uuid.uuid4().hex[:16]}",
            semantic_identity=semantic_identity,
            explanation=explanation,
            context=(),
            supporting_artifacts=tuple(supporting_evidence),
            contradicting_artifacts=tuple(contradicting_evidence or []),
            confidence=confidence,
            uncertainty=uncertainty,
            created_at_utc=time.time(),
            generated_by=generated_by,
        )
    
    def with_context(self, context: List[str]) -> "ReasoningHypothesis":
        """Return a copy with added context references."""
        return dataclass_replace(
            self,
            context=context if isinstance(context, tuple) else tuple(context),
        )
    
    def update_confidence(self, new_confidence: float, new_uncertainty: Optional[float] = None) -> "ReasoningHypothesis":
        """Return a copy with updated confidence and uncertainty."""
        return dataclass_replace(
            self,
            confidence=new_confidence,
            uncertainty=new_uncertainty if new_uncertainty is not None else 1.0 - new_confidence,
        )


@dataclass(frozen=True)
class HypothesisEvaluation:
    """
    Evaluation of a reasoning hypothesis.
    
    An evaluation considers:
        - Supporting evidence strength
        - Contradicting evidence
        - Consistency with known beliefs
        - Confidence and uncertainty assessments
    """
    
    # Identity
    evaluation_id: str                      # Unique evaluation identifier
    
    # Target
    evaluated_hypothesis: str               # Which hypothesis was evaluated?
    
    # Assessment
    supporting_artifacts: Tuple[str, ...]   # Evidence that supports
    contradicting_artifacts: Tuple[str, ...] = ()  # Evidence against
    
    # Quality measures
    confidence: float = 0.5                 # Confidence in the hypothesis
    uncertainty: float = 0.3                # Remaining uncertainty
    consistency_score: float = 1.0          # Consistency with known beliefs
    
    # Timing
    evaluated_at_utc: float = field(default_factory=time.time)
    
    # Provenance
    evaluator: str = "unknown"              # Who/what performed evaluation?
    provenance: Dict[str, str] = field(default_factory=dict)
    
    @property
    def is_supported(self) -> bool:
        """Check if hypothesis has sufficient supporting evidence."""
        return self.confidence >= 0.7 and len(self.supporting_artifacts) > 0
    
    @property
    def is_confirmed(self) -> bool:
        """Check if hypothesis is strongly supported with low uncertainty."""
        return self.confidence >= 0.85 and self.uncertainty <= 0.15
    
    @classmethod
    def create(
        cls,
        evaluated_hypothesis_id: str,
        supporting_evidence: List[str],
        contradicting_evidence: Optional[List[str]] = None,
        confidence: float = 0.5,
        uncertainty: float = 0.3,
        consistency_score: float = 1.0,
    ) -> HypothesisEvaluation:
        """Create a new evaluation."""
        return cls(
            evaluation_id=f"evaluation:{uuid.uuid4().hex[:16]}",
            evaluated_hypothesis=evaluated_hypothesis_id,
            supporting_artifacts=tuple(supporting_evidence),
            contradicting_artifacts=tuple(contradicting_evidence or []),
            confidence=confidence,
            uncertainty=uncertainty,
            consistency_score=consistency_score,
        )


def dataclass_replace(instance: Any, **kwargs: Any) -> Any:
    """Simple dataclass replace helper for frozen instances."""
    return instance.__class__(**{**instance.__dict__, **kwargs})


__all__ = [
    "ReasoningHypothesis",
    "HypothesisEvaluation",
]